[package]
name = "birthcal"
version = "0.1.0"
edition = "2024"
rust-version = "1.86.0"
license = "AGPL-3.0"
authors = ["Alexander A. Klimov <a@kli.mov>"]

[dependencies]
cgi = "0.8.0"
html = "0.6.3"
ical = "0.11.0"
percent-encoding-rfc3986 = "0.1.3"
regex = "1.11.2"
ureq = "3.1.1"
