[package]
name = "birthcal"
version = "0.1.0"
edition = "2021"
rust-version = "1.82.0"
license = "AGPL-3.0"
authors = ["Alexander A. Klimov <a@kli.mov>"]

[dependencies]
chrono = "0.4.41"
cgi = "0.7.2"
html = "0.6.3"
ical = "0.11.0"
percent-encoding-rfc3986 = "0.1.3"
ureq = "3.0.11"
